services:
  web:
    build: .
    volumes:
      - ./data:/data
      - certs:/certs
      - ./challenge:/challenge/:ro 
      - ./challenge_cache:/challenge_cache/:ro 
    environment:
      FLASK_DEBUG: 0
      DOCKER_TLS_CERTDIR: /certs
    env_file:
      - .env
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - ./challenge:/challenge/:ro 
      - ./challenge_cache:/challenge_cache/:ro
      - certs:/certs
volumes:
  certs: