services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./data:/data
      - certs:/certs
      - ./challenge:/challenge/:ro 
      - ./challenge_cache:/challenge_cache/:ro 
    environment:
      FLASK_APP: "app.py"
      FLASK_DEBUG: 1
      DOCKER_TLS_CERTDIR: /certs

  dind:
    image: docker:dind
    privileged: true
    volumes:
      - ./challenge:/challenge/:ro 
      - ./challenge_cache:/challenge_cache/:ro
      - certs:/certs
volumes:
  certs: