services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"

  dind:
    image: docker:dind
    privileged: true
    volumes:
      - ./challenge:/challenge/:ro  # Read-only volume for Dockerfiles
    command: ["dockerd"]
